# ================= KEY BINDINGS =================
# Change the prefix key to C-x
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Move pane like vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Split window
bind , split-window -h
bind . split-window -v

# ================= STATUS BAR =================
# Bbackground and text color
set -g status-style bg="#1e2030",fg="#a9b1d6"

# Right section (date and time)
set -g status-right "#[fg=#7dcfff] %Y-%m-%d #[fg=#8bbdf7]%H:%M #[default]"

# ================= STYLE =================
# Active window display
set -g window-status-current-style fg="#7aa2f7",bg="#1e2030",bold

# Customize window list separator
set -g window-status-separator " #[fg=#3b4261]|#[default] "

# Inactive window display
set -g window-status-style fg="#a9b1d6",bg="#1e2030"

# Message display (prefix or copy mode)
set -g message-style bg="#bb9af7",fg="#1e2030",bold

# Message display for commands (warnings or errors)
set -g message-command-style bg="#f7768e",fg="#1e2030",bold

# Pane border color
set -g pane-border-style fg="#3b4261"
set -g pane-active-border-style fg="#7aa2f7"

# Style for copy mode
set -g mode-style bg="#3b4261",fg="#c0caf5",bold

# Tmux clock mode color
set -g clock-mode-colour "#8bbdf7"
